/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.laberintos.view;

import ucr.ac.cr.laberintos.controller.ControladorPrincipal;

/**
 *
 * @author Usuario
 */
public class GUIHistoria extends javax.swing.JFrame {

    /**
     * Creates new form GUIHistoria
     */
    
    private ControladorPrincipal controlador;
    private GUIFrame guiFrame;
            
            
    public GUIHistoria(ControladorPrincipal controlador, GUIFrame guiFrame) {
        initComponents();
        this.controlador=controlador;
        this.guiFrame=guiFrame;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsalirHistoria = new javax.swing.JButton();
        lblHistoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsalirHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnsalirHistoria.setText("jButton1");
        btnsalirHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalirHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 220, 50));

        lblHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historia.png"))); // NOI18N
        lblHistoria.setText("jLabel1");
        getContentPane().add(lblHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -10, 672, 763));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirHistoriaActionPerformed
        controlador.mostrarMenuPrincipal(); 
        setVisible(false); 
    }//GEN-LAST:event_btnsalirHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalirHistoria;
    private javax.swing.JLabel lblHistoria;
    // End of variables declaration//GEN-END:variables
}
